repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        require_serial: true
        types: [python]
        always_run: true
      - id: pytest-check
        name: pytest-check
        entry: "pytest tests"
        language: system
        pass_filenames: false
        always_run: true
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        require_serial: true
