"""Event manager file"""


class Event:
    """
    A superclass for any events that might be generated by an
    object and sent to the EventManager.
    """

    def __init__(self):
        """Constructor"""
        self.name = "Generic event"

    def __str__(self):
        """Return name with printed"""
        return self.name


class QuitEvent(Event):
    """
    Quit event.
    """

    def __init__(self):
        self.name = "Quit event"


class TickEvent(Event):
    """
    Tick event.
    """

    def __init__(self):
        self.name = "Tick event"


class ClickEvent(Event):
    """
    Click event.
    """

    def __init__(self, location: tuple):
        """
        Constructor for ClickEvent
        location:tuple = (y,x) which represent board squares
        """
        self.name = "Click event"
        self.location = location


class EventManager:
    """this object is responsible for coordinating most communication
    between the Model, View, and Controller."""

    def __init__(self):
        """Constructor"""
        from weakref import WeakKeyDictionary

        self.listeners = WeakKeyDictionary()

    def register_listener(self, listener):
        """Register a listener to listen for events"""
        self.listeners[listener] = 1

    def unregister_listener(self, listener):
        """Remove a listener"""
        if listener in self.listeners.keys():
            del self.listeners[listener]

    def post(self, event):
        """Function that notifies all listers of new event"""
        for listener in self.listeners.keys():
            # NOTE: If the weakref has died, it will be
            # automatically removed, so we don't have
            # to worry about it.
            listener.notify(event)
